branches:
  except:
    - travis

install:
  - git submodule update --init --recursive
build_script:
  - ps: Update-AppveyorBuild -Version "$(git describe --dirty=-d)-$env:APPVEYOR_BUILD_NUMBER"
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

test: off
deploy: off

configuration:
  - Debug
  - Release

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  nodejs_version: "10"
  matrix:
    - RWE_COMPILER: MSYS
    - RWE_COMPILER: MSVC

matrix:
  fast_finish: true

cache:
  - libs\_protobuf-install
